### PR TITLE
Fixes #151 add unit tests for python modules

### LINKED ISSUE #151: Add unit tests for python modules
### Current behaviour

The python modules are not tested.

### Expected behaviour

unit tests should be added for travis to run them.

### PR DESCRIPTION
**Pull request by pri22296**
## Description

- Unit tests are added for modules `genindex.py`,  `linkfix.py`, `config.py`
- Removed the unnecessary `modules/requirements.txt`. Used the `requirements.txt` at the root in `generate.sh`

## Related Issue

#151 

## Motivation and Context

Unit tests are required to ensure that existing functionality does not break with updates

## Screenshots (if appropriate):
screenshot 156

## Types of changes

- [ ] Bug fix 
- [ ] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by pri22296** [comment]
@sch00lb0y @imujjwal96 Please review

**Comment by pri22296** [comment]
@sch00lb0y @imujjwal96 Could you please review this PR

**Comment by pri22296** [comment]
I added partly because more tests would be needed in the future so didn't wanna close the issue

**Comment by imujjwal96** [comment]
You may create specific issues for those changes.

**Pull request merged**
