### PR TITLE
Fixes #342: adding support for sending notification if access token revoked

### LINKED ISSUE #342: send a notification as a mail if access token revoked
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

send a notification saying that access_token revoked and also ask the user to signin once again to continue the service
### Steps to reproduce
1.
2.
3.

### PR DESCRIPTION
**Pull request by sch00lb0y**
## Description

added support to send notification if the user access token revoked.
## Types of changes

- [ ] Bug fix 
- [x] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by imujjwal96** [comment]
What is this PR? What does it do? Neither the issue nor this PR explain clearly what the issue is and how it is solved. I hope if you could be a bit more verbose in your issues and their PR

**Comment by sch00lb0y** [comment]
@imujjwal96 if user revokes the access token documentation deployment won't happen so every 24 hours it'll check any of the users revoked the access token. if user revoked it send a email to the user saying that access token revoked sign in again to continue the service

**Comment by pri22296** [comment]
@sch00lb0y Is this really needed?

**Comment by sch00lb0y** [comment]
Actually, I have sent the PR long back. and also it is a small PR. anyway, work is done. no harm in merging :sweat_smile:

**Comment by pri22296** [comment]
@sch00lb0y If that's the case, I guess it's fine. I do want to know that whether this would require too much resources? Also do you know what does travis do in a similar case?

**Comment by sch00lb0y** [comment]
@pri22296 I'm queuing the job so it won't run multiple request at a time. even I made in a way that we can replace the current queue with redis queue if we care about scalability(no need to worry about this now). I don't know about travis. But I had got a notification like this from codetriage. it won't spam as well it'll send only once

**Comment by pri22296** [comment]
@sch00lb0y Thanks for the explanation. I guess I'll need to test this once. How long before the mail is recieved?

**Comment by pri22296** [comment]
@sch00lb0y Any update on this?

**Comment by sch00lb0y** [comment]
shall I close this now? I'm not able to register sendgrid

**Comment by sch00lb0y** [comment]
@pri22296 Actually when I try to create send grid account. It showing me error. so i cant' show deployment :cry: :cry:

**Comment by pri22296** [comment]
Ok, Maybe discuss once with @imujjwal96

**Comment by imujjwal96** [comment]
@sch00lb0y Do one thing! Raise another issue to extend SMTP to other services as well! Solve that first and then test this

**Comment by pri22296** [comment]
@sch00lb0y Now that #418 is merged, any other blocker for this PR?

**Comment by sch00lb0y** [comment]
@pri22296 @imujjwal96 I have updated this PR please check http://demo08.herokuapp.com/ :smile:

**Comment by mariobehling** [comment]
Can this be merged?

**Comment by mariobehling** [comment]
@sch00lb0y We have changed the default branch to development some time ago. Could you make this PR again for development, please?

**Comment by niranjan94** [comment]
@sch00lb0y please update the branch

**Pull request closed without merging**
