### PR TITLE
Fixes #176 update using ssh section of the README

### LINKED ISSUE #176: README Using SSH section is misleading
https://github.com/fossasia/yaydoc#using-ssh is misleading on the last step, it doesn't instruct the user to change the key and the initialization vector variable names.

Travis doesn't use the same variables for every repository, the hashes in the middle of it (`encrypted_<hash>_key` and `encrypted_<hash>_iv`) are different for every repo.

Please change it, since a lot of people will ask why their "decrypted" keys results is not an SSH key but what you would expect from `/dev/urandom`.

### PR DESCRIPTION
**Pull request by pri22296**
## Related Issue

Fixes #176

## Types of changes

- [ ] Bug fix 
- [ ] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by pri22296** [comment]
@yukiisbored @sch00lb0y @imujjwal96 Please review

**Comment by sch00lb0y** [comment]
@pri22296 could u change the travis example section.
`./generate.sh` to `./generate_ci.sh`

**Comment by imujjwal96** [comment]
I hope you wouldn't mind updating the example blocks from `script` to `deploy` and `before_deploy`, as the service we provide should be performed after the tests performed in Travis are successful

**Comment by pri22296** [comment]
@sch00lb0y @imujjwal96 I have made the changes

**Pull request merged**
