### PR TITLE
Partly Fixes #85 Setup framework with basic configs

### LINKED ISSUE #85: Create a web ui which enable documentaion generation
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

right now yaydoc is creating documentation from travis build.
### Expected behaviour

create a web ui which enable user to create documentation.

### PR DESCRIPTION
**Pull request by imujjwal96**
## Description

I have set up the ExpressJS framework for the WebUI. The directory structure used is generated using the [express-generator](https://www.npmjs.com/package/express-generator). 
A duplicate of the original generate script is added with some changes so that the script could align with the functionality of the WebUI. It was also done so that the original script may continue to work with no interference from the WebUI 

## Related Issue

issue: #85 

## How Has This Been Tested?

I have deployed the app at http://yaydoc.tk

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix 
- [x] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [ ] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by imujjwal96** [comment]
@pri22296 @sch00lb0y @niranjan94 @mariobehling 
Please review.

**Comment by imujjwal96** [comment]
there are several known issues which are to be worked on. 
1. The WebUI doesn't work with heroku yet, because of the request timeout (As the documentation generator takes time greater than 30s before returning any response). Will have to work with socket.io so that we simultaneously get responses from the server, similar to the logs in open-event
2. I haven't done much validation with the form input yet.
3. The docs are only generated in a temp folder, will have to extract it from their to "download as zip" or perform other tasks

**Comment by sch00lb0y** [comment]
@imujjwal96 just a suggestion. could you use ejs as a templating engine because jade make thing complicated. see the [conversation](https://stackoverflow.com/questions/16513168/what-are-the-pros-and-cons-of-both-jade-and-ejs-for-node-js-templating). if we want to use jade  no problem, we'll use it

**Comment by imujjwal96** [comment]
There isn't much work to do with HTML on the front-end. I don't think Jade would be an issue

**Comment by pri22296** [comment]
@imujjwal96 I agree. Let's go with Jade for now. Usage of HTML would anyways be minimal with the webUI. If any need be in the future, we'll switch to another templating engine.

**Comment by pri22296** [comment]
@imujjwal96 Looks good. I just have a doubt. How will further development on the generate script go. do we have to keep both of them in sync?

**Comment by imujjwal96** [comment]
I have the same concern. What I can think of right now is that we will update the generate script of the WebUI whilst adding functionalities, keeping the original script separated from it.

**Comment by pri22296** [comment]
any specific reason to use arguments instead of environment variables?

**Comment by imujjwal96** [comment]
None.

**Comment by pri22296** [comment]
So could we set up the WebUI stuff in a different script and call the generate script from there? maybe make some modification to the generate script itself if needed so that it works from both travis and the web ui.

**Comment by sch00lb0y** [comment]
@imujjwal96 please solve codacy issues

**Pull request merged**
