### PR TITLE
Fixes #295 Create a dashboard for Yaydoc CI

### LINKED ISSUE #295: Create a dashboard for Yaydoc CI
### This is a
- [ ] Bug report
- [x] Feature request

### Description
With the current implementation, when the user logs in to Yaydoc CI, a modal is opened. There are several limitations and issues to the current implementation.
* If the modal is closed mistakenly, the user will again have to Sign in to the Yaydoc CI to get that modal again. This wastes a lot of time and resources and can be frustrating to the user.
* As @pri22296 mentioned (https://github.com/fossasia/yaydoc/pull/285#issuecomment-317170101) 'Clicking on one-time deployment is taking me to CI-deployment window.' This is because the user is presumably signed in for CI deployment and hence Callback assumes that the user wants to CI Deploy. This is undesirable.
* There is no log out functionality from CI deployment, hence, the issue mentioned in point 2 cannot be solved.
* With further development of the project, many new features will be added to CI Deployment which cannot be handled from a single modal

### PR DESCRIPTION
**Pull request by imujjwal96**
## Description

* Setup user model
* Implemented user authentication in Yaydoc
* Implemented Logout functionality
* Setup dashboard
* Refactored CI portion and moved to dashboard
## Related Issue

Fixes #295 
## Motivation and Context

With the current implementation, when the user logs in to Yaydoc CI, a modal is opened. There are several limitations and issues to the current implementation.
* If the modal is closed mistakenly, the user will again have to Sign in to the Yaydoc CI to get that modal again. This wastes a lot of time and resources and can be frustrating to the user.
* As @pri22296 mentioned (#285 (comment)) 'Clicking on one-time deployment is taking me to CI-deployment window.' This is because the user is presumably signed in for CI deployment and hence Callback assumes that the user wants to CI Deploy. This is undesirable.
* There is no log out functionality from CI deployment, hence, the issue mentioned in point 2 cannot be solved.
* With further development of the project, many new features will be added to CI Deployment which cannot be handled from a single modal

## How Has This Been Tested?

Test at https://yaydoc6.herokuapp.com
## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix 
- [x] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by imujjwal96** [comment]
@pri22296  @sch00lb0y Please review

**Comment by pri22296** [comment]
@imujjwal96 Please consider the following points

- Register button can be clicked even when when no repository is searched for.
- Rename the Label `Organization` to `Username/Organization`
- A better flow would be to just have a sign-in button and keep the user in start page on sign-in and just enable two buttons for the dashboard and sign-out.

**Comment by imujjwal96** [comment]
@pri22296  The user will sign-in to register repository to yaydoc.  I cannot think of a reason to keep to user on the start page

**Comment by imujjwal96** [comment]
@pri22296 Updated

**Comment by mariobehling** [comment]
Nice work!

**Pull request merged**
