### PR TITLE
Fixes #278 Handle embedded html links

### LINKED ISSUE #278: Side by side images in markdowns
### This is a
- [x] Bug report
- [ ] Feature request

### Description
One of the popular method for adding side by side images in Github markdown is to use HTML. Unfortunately, these images are not rendered in the generated static websites. 
http://yaydoc.herokuapp.com/preview/ujjwalb1996@gmail.com/d7a044d8-d5c8-422d-af71-8e6465f62a8f_preview/

image
image

### PR DESCRIPTION
**Pull request by pri22296**
## Description

Now all documents included via directives will be scanned or any html tags with `src` attribute and the value for that attribute if detected to be a relative link would be modified to handle relative paths upon include.

## Related Issue

Fixes #278 

## How Has This Been Tested?

Deployment: http://yaydoc278.herokuapp.com/
Generated docs: http://yaydoc278.herokuapp.com/preview/priyamsingh.22296@gmail.com/59718106-36dd-4dff-a67c-ee053ca46ff0_preview/

## Screenshots (if appropriate):
screenshot 187

## Types of changes

- [x] Bug fix 
- [x] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by pri22296** [comment]
@imujjwal96 @sch00lb0y Please review

**Comment by imujjwal96** [comment]
what if the user stores the image at a path other that the source specified?

**Comment by pri22296** [comment]
Do you mean that what if the user doesn't store the image in `_static`?

**Comment by imujjwal96** [comment]
Oh! that constraint is there. Please update the README :)

**Comment by pri22296** [comment]
@imujjwal96 updated

**Pull request merged**
