### PR TITLE
Fixes #288 Add support for index in markdown

### LINKED ISSUE #288: Support Index in markdown format
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

The index file which becomes the starting page of the generated docs is still required to be ReST.

### Expected behaviour

Markdown format should also be supported

### PR DESCRIPTION
**Pull request by pri22296**
## Description

Experimental support for **index.md**

- Also added `auto_toc_tree` which convert bulleted links to documents into a toctree.
- `eval_rst` can be used for some features which aren't available in markdown. Although using `mdinclude` directive does not work properly when the included documents have titles as Titles aren't handled by `eval_rst`. Created Issue for that at https://github.com/rtfd/recommonmark/issues/79

## Related Issue

Fixes #288

## How Has This Been Tested?

Deployment: https://yaydocmd.herokuapp.com

## Types of changes

- [ ] Bug fix 
- [x] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by pri22296** [comment]
@imujjwal96 @sch00lb0y Please review. There is an issue with headings not being handled by `eval_rst` that means that if the included README contains headings, they would be omitted. Also the `auto_toc_tree` will always convert bulleted list of links to documents into a toctree even when it is not intended. I could add a constraint there that only convert if under a section named `Contents`. should that be done?

**Comment by imujjwal96** [comment]
Yes! That would be nice.

**Comment by pri22296** [comment]
@imujjwal96 updated

**Comment by imujjwal96** [comment]
How am is supposed to test it?
Also, can you update the README?

**Comment by pri22296** [comment]
You can test it by providing an `index.md` in your test repository. Here's a sample [index
](https://raw.githubusercontent.com/pri22296/testYaydoc2/master/docs/index.md). Ignore the eval_rst block. 
Will update the README

**Comment by imujjwal96** [comment]
@pri22296  This index.md will be inside the source path, right?
Will it be possible if the user defines the # Content  title in the README.md at root, the content inside it will be taken as a toc tree?

**Comment by pri22296** [comment]
Yes the index.md would be inside sourcepath. It won't work from the README. This is because the README is handled by pandoc and not by recommonmark. And the `auto_toc_tree`, `eval_rst` features are provided via recommonmark.

**Comment by imujjwal96** [comment]
Update the README then. Looks good to me

**Comment by pri22296** [comment]
@imujjwal96 Updated

**Pull request merged**
