### PR TITLE
Fixes #339 #340 Update github pages deployment

### LINKED ISSUE #339: Remove commit history from gh-pages branch
### This is a
- [x] Bug report
- [ ] Feature request

### Current behaviour

When docs are deployed to github pages branch for the first time, the commit history is retained. This creates fake commits which would be undesirable.
### Expected behaviour

When a new gh-pages branch is created, start from 1st commit.

### Screenshot
image

### PR DESCRIPTION
**Pull request by imujjwal96**
## Description

* used `git checkout --orphan`
* taking username from req.user
## Related Issue

Fixes #339  #340
## How Has This Been Tested?

Test at https://yaydoc6.herokuapp.com

## Types of changes

- [x] Bug fix 
- [ ] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by pri22296** [comment]
@imujjwal96 The detailed logs should be a superset of the logs displayed in the console, right?

<table>
<tr>
<td>
</td>
<td>
</tr>
</table>

**Comment by imujjwal96** [comment]
Oh! I forgot to update the deployment. Pardon me!

**Comment by imujjwal96** [comment]
@pri22296 updated

**Comment by pri22296** [comment]
@imujjwal96 Please resolve conflicts

**Comment by imujjwal96** [comment]
@pri22296  Updated.

**Pull request merged**
