### PR TITLE
Fixes #393 add swagger, twitter and rss to autoindex

### LINKED ISSUE #393: Add swagger ui, rss feed and twitter feed to the auto-generated index
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

Currently links to those should be manually added to the index.

### Expected behaviour

#372 implemented a system for configuring the behaviour of the auto-generated index. Using that, add the mentioned links to the index if specified.

### PR DESCRIPTION
**Pull request by pri22296**
## Description

- Added option to add the directives for blog and twitter to auto-generated index
- Added swagger UI link to auto-generated index

## Related Issue

Fixes #393

## How Has This Been Tested?

Deployment: https://yaydocx.herokuapp.com

## Types of changes

- [ ] Bug fix 
- [x] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by imujjwal96** [comment]
Can you show us a sample deployment?

**Comment by pri22296** [comment]
@imujjwal96 Preview : https://yaydocx.herokuapp.com/preview/priyamsingh.22296@gmail.com/7405add8-959c-4bbd-a7ae-298f56ac7207_preview/

The yaml file used: https://github.com/pri22296/testYaydoc2/blob/apidoc/.yaydoc.yml

Tweets and blog aren't loading due to some issue which @sch00lb0y would be better able to explain

**Comment by imujjwal96** [comment]
@pri22296 @sch00lb0y is that issue fixed now?

> Tweets and blog aren't loading due to some issue which @sch00lb0y would be better able to explain

**Comment by sch00lb0y** [comment]
@imujjwal96 tweet and blogs are not loading because of https

**Comment by imujjwal96** [comment]
Cam you please elaborate?

**Comment by sch00lb0y** [comment]
@imujjwal96 in cloud deployment we using https so it blocking all http connection. but it'll work in local deployment

**Comment by pri22296** [comment]
@imujjwal96 That shouldn't block this PR though

**Pull request merged**
