### PR TITLE
Use a virtual environment to prevent permission denied error

### LINKED ISSUE #29: [Question] Is it mandatory to configure travis with language set to python?
In the documentation of this project, it is mentioned that I have to configure my travis as follow: 
image

My question is, since I have a project in PHP which uses travis to build unit tests, I have to set PHP as my language. How would yaydoc integrate with my project then?

### PR DESCRIPTION
**Pull request by pri22296**
Fixes #29 

## Additional fixes

- Fixed error on Python2.7
- Introduced yaydocclone and copy only required folders to yaydoctemp from it. Otherwise, README.md file of the this repo was being accidently built by sphinx and pushed to gh-pages branch.

### CODE REVIEW

**Comment by pri22296** [comment]
@niranjan94 @sch00lb0y @imujjwal96 Please review

**Comment by imujjwal96** [comment]
@pri22296 It seems to be failing. 
Can you have a look at [this](https://travis-ci.org/imujjwal96/prelimQuiz/jobs/234067671)?

**Comment by sch00lb0y** [comment]
@imujjwal96 can you check whether you have mentioned correct doc path env var in travis

**Comment by imujjwal96** [comment]
@sch00lb0y I didn't set DOCPATH. Since the README.md file is in the root directory of the project, I was hoping that by default we consider the root directory.

**Comment by pri22296** [comment]
@imujjwal96 The generate.sh which you are calling clones fossasia/yaydoc. Since the PR hasn't been merged, this repo does not have those updated files. Also you need to set the docs path.

**Comment by imujjwal96** [comment]
Can you make a branch with setting local to you. It will be easier to test this PR and other PR's from your repository.

Also, what should I set docs DOCPATH to?

**Comment by pri22296** [comment]
set DOCPATH as /
Also I have created a new branch named test which clones from my fork

**Comment by pri22296** [comment]
@imujjwal96 Also there is no index.rst. sphinx needs one to generate docs

**Comment by imujjwal96** [comment]
@pri22296 But the documentation doesn't mention the presence of an index.rst file in my project. 
I think it wouldn't be wise to let such a thing be left under assumption.

**Comment by pri22296** [comment]
@imujjwal96 Basically we need a directory with all markup files and an index.rst which contains toctrees to link the various documents. Basically what sphinx requires. could you add it to the README??

**Comment by imujjwal96** [comment]
Surely.

**Comment by imujjwal96** [comment]
@pri22296 Not working >.<  Made the changes and set DOCPATH = docs
https://travis-ci.org/imujjwal96/prelimQuiz/jobs/234101820

Branch: https://github.com/imujjwal96/prelimQuiz/tree/docs

**Comment by pri22296** [comment]
@imujjwal96 could you set DOCPATH = docs/

**Comment by imujjwal96** [comment]
One caveat more. Need to create the gh-pages repository manually.

**Comment by pri22296** [comment]
@imujjwal96 yeah creating gh-pages branch if not already present would be nice addition.

**Pull request merged**
