### PR TITLE
Fixes part of #8 added primary implementation for reading configuration from .yaydoc.yml

### PR DESCRIPTION
**Pull request by pri22296**
## Description

Read configuration options from file named `.yaydoc.yml` from repository if present. If environment variables are also specified, they take precedence. Currently it is assumed that the corresponding environmental variable's name of a configuration variables is just in upper case.
for example, either specify `docpath` in `.travis.yml` or create a environment variable named `DOCPATH`.
the file is divided into 3 sections
- metadata( for info such as version, project name, etc)
- build(variable which configure certain properties of the build process) 
- publish(contains subsections for various publishers supported, currently only ghpages)

Here's an sample `.yaydoc.yml`

```yaml
metadata:
  projectname: Yaydoc
  author: FOSSASIA
  version: development
  
build:
  markdown_flavour: markdown_github
  docpath: docs/
  doctheme: fossasia

publish:
  ghpages:
    docurl: yaydoc.fossasia.org
```

## Related Issue

#8

## Motivation and Context

Having a dedicated file for specifying configuration will be easier for the users. Also as the projects continues to grow, more number of configuration variables will be needed. It is not feasible for user to input all of them in the webUI. This approach would be easier to setup.

## How Has This Been Tested?

Tested on my test repository
Build log: https://travis-ci.org/pri22296/testYaydoc2

## Types of changes

- [ ] Bug fix 
- [x] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by pri22296** [comment]
@imujjwal96 @sch00lb0y please review

**Comment by sch00lb0y** [comment]
@pri22296 please check the codacy issue

**Comment by pri22296** [comment]
@sch00lb0y I have fixed the codacy issue

**Comment by pri22296** [comment]
sure

**Comment by pri22296** [comment]
@sch00lb0y I have updated the README

**Comment by mariobehling** [comment]
Good job!

**Pull request merged**
