### PR TITLE
Fixes #357 Create settings page for repositories

### LINKED ISSUE #357: Edit registered repository's configuration
### This is a
- [ ] Bug report
- [x] Feature request

### Description

A registered repository can only be enabled, disabled or deleted. There is no option of editing its configurations. Some of these configurations include disabling build status mail service, update hooks, update registrant etc.

### PR DESCRIPTION
**Pull request by imujjwal96**
## Related Issue

issue #357 

## How Has This Been Tested?

https://yaydoc7.herokuapp.com/
## Types of changes

- [ ] Bug fix 
- [x] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by pri22296** [comment]
@imujjwal96 Is there a way to remove the stored logs for my registered repo?

**Comment by imujjwal96** [comment]
why would we need that?

**Comment by pri22296** [comment]
No, we don't need that. I needed to test this PR when no logs have been generated and couldn't find a way to remove the logs.

**Comment by pri22296** [comment]
@imujjwal96 Application crashes after trying to check the log for a repo where no logs exist.

**Comment by imujjwal96** [comment]
@pri22296 Apparently, the issue seems to be much bigger than thought. This PR having not much related to the issue, I hope you wouldn't mind if I work on that separately.

**Comment by sch00lb0y** [comment]
The main reason we raised this issue is to edit the sub project configuration after the user intial registration as we disscussed in the PR https://github.com/fossasia/yaydoc/pull/318 so it would be great if we merge PR https://github.com/fossasia/yaydoc/pull/318 before this PR @imujjwal96 your opinion ?

**Comment by imujjwal96** [comment]
Neither the issue nor this PR mentions anything about editing sub projects configuration. What I have done here apart from adding some configurable option, is given a platform(route) where we can make many other things configuration, including sub projects' configuration.

**Comment by sch00lb0y** [comment]
@imujjwal96 No issue I just asked your opinion on merging. Good Work !!

**Pull request merged**
