### PR TITLE
set up configuration to input subproject's urls and docpath

### PR DESCRIPTION
**Pull request by pri22296**
## Description

- add two new env var `SUBPROJECT_URLS` and `SUBPROJECT_DOCPATHS` which would contain `comma` seperated urls and docpaths respectively.
A user would be able to set it from the `.yaydoc.yml` file like this

```yaml
metadata:
  projectname: testYaydoc2
  author: Priyam Singh
  debug: true
  subproject:
    - url: https://github.com/testYaydoc2.git
      docpath: 'docs'
    - url: https://github.com/testYaydoc.git
      docpath: 'doc'
```

Resultant output
```bash
export DOCTHEME="fossasia_theme"
export SUBPROJECT_DOCPATHS="docs,doc"
export SUBPROJECT_URLS="https://github.com/testYaydoc2.git,https://github.com/testYaydoc.git"
export MARKDOWN_FLAVOUR="markdown_github"
export LOGO=""
export AUTHOR="Priyam Singh"
export VERSION="Jun 21, 2017"
export DOCPATH="docs"
export PROJECTNAME="testYaydoc2"
```

## Related Issue

#160 

## Motivation and Context

This is required so that user's would be easily able to specify subprojects

## Types of changes

- [ ] Bug fix 
- [x] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by pri22296** [comment]
@imujjwal96 @sch00lb0y Please review

**Comment by imujjwal96** [comment]
Can you show how these Env Vars would look with your example yaml

**Comment by pri22296** [comment]
@imujjwal96 I have updated the description with the output

**Comment by imujjwal96** [comment]
@pri22296  any token to check if subprojects exist? Or the presence of values in these two env vars is enuff?

**Comment by pri22296** [comment]
That logic would have to be handled by the script which clones the subprojects. I think config.py should be limited to reading values from `.yaydoc.yml` and exporting env vars from that.

**Comment by imujjwal96** [comment]
@pri22296  What about the name of the subprojects?

**Comment by pri22296** [comment]
For now let's default with the repository name? or maybe i could add an extra field for it and default it with reponame extracted from the url? any other fields we should expose in the subproject section?

**Comment by imujjwal96** [comment]
I don't think so

**Comment by pri22296** [comment]
okay a query! where would we need the subproject's name in the build process?

**Comment by imujjwal96** [comment]
I guess we won't :ok_hand:

**Pull request merged**
