### PR TITLE
Fixes #64: pylint configuration added

### LINKED ISSUE #64: Add linter to build system
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour
right now yaydoc not having code style checker in build system. so it leads to manual check

### Expected behaviour

integrate linter in build system

### Steps to reproduce
1. add the code style to codacy

### PR DESCRIPTION
**Pull request by sch00lb0y**
## Description
pylint configuration added so codacy will automatically do lint check on each pull request
close #64 
## Related Issue

#64 
## Motivation and Context

if we add this there won't be any manual lint check. codacy will be automatically will check the lint errors
## Types of changes

- [ ] Bug fix 
- [x] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by pri22296** [comment]
Is this the default pylintrc file or have you made any changes to it?

**Comment by imujjwal96** [comment]
@pri22296 I hope you won't mind if I test yaydoc by deploying it once.

**Comment by sch00lb0y** [comment]
yeah it is default one

**Comment by pri22296** [comment]
Then do we need to supply the default rc file for codacy to work?

**Comment by sch00lb0y** [comment]
Yeah, codacy will automatically detect and do the lint check.

**Pull request merged**
