### PR TITLE
Fixes #350 Add support to add disqus comments

### LINKED ISSUE #350: Add option to add disqus comments in the generated docs
### This is a
- [ ] Bug report
- [x] Feature request

### Expected behaviour

Users would be able to add disqus comments on any page using a simple directive.

### Steps to reproduce
1.
2.
3.

### PR DESCRIPTION
**Pull request by pri22296**
## Description

- Added `disqus` directive to enable disqus comments.
- Updated genindex.py so that if disqus.short_name is provided, adds disqus comments at the bottom of the page.

## Related Issue

Fixes #350 

## How Has This Been Tested?

Deployment: https://yaydocmd.herokuapp.com

## Screenshots (if appropriate):
screenshot 202

## Types of changes

- [ ] Bug fix 
- [x] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by pri22296** [comment]
@sch00lb0y @imujjwal96 Please review

**Comment by imujjwal96** [comment]
Can you show a sample deployed docs?

**Comment by pri22296** [comment]
@imujjwal96 https://yaydocmd.herokuapp.com/preview/priyamsingh.22296@gmail.com/b643ff54-0f63-477f-bfc6-c29951f5de89_preview/

**Comment by mariobehling** [comment]
Why do we need this? Low priority and probably not needed. Please focus on priority issues. We need the documentation of all FOSSASIA projects up and running. What is going on? Why don't we have this and now have to spend time on reviewing this?

**Pull request closed without merging**
