### PR TITLE
Fixes #109 runs sphinx-apidoc for python projects

### LINKED ISSUE #109: Run sphinx-apidoc for python based projects
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

[sphinx-apidoc](http://www.sphinx-doc.org/en/stable/man/sphinx-apidoc.html) is not run

### Expected behaviour

sphinx provides a sphinx-apidoc command for python based projects to extract docstrings from the modules. It should be run to use that feature.

### PR DESCRIPTION
**Pull request by pri22296**
## Description

added call to [sphinx-apidoc](http://www.sphinx-doc.org/en/stable/man/sphinx-apidoc.html) if PYTHON_PACKAGE is defined.

## Related Issue

Fixes #109 

## Motivation and Context

For python based projects, sphinx provides an extra capability to generate apidoc similar to Java's javadoc. This PR adds that functionality to yaydoc.

## How Has This Been Tested?

Tested on travis + local webUI

## Types of changes

- [ ] Bug fix 
- [x] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by pri22296** [comment]
@sch00lb0y @imujjwal96 Please review

**Comment by imujjwal96** [comment]
@pri22296 honestly, i am not well versed with Python. So I can't properly review this PR. My apologies.

**Comment by pri22296** [comment]
@sch00lb0y I have made the changes to the README

**Comment by imujjwal96** [comment]
@niranjan94  Please review this.

**Pull request merged**
