### PR TITLE
added new directive mdinclude to include markdown files

### LINKED ISSUE #12: Implement way to directly generate a sphinx documenation site with md files instead of rst files
The current way of creating a documentation site is as follows:
1. Usually repositories use md files on Github 
2. In a project developers then convert the files to rst files manually or automatically (Readme.md to rst and /docs folder files)
3. In the next step a site in a desired repository or location is generated

In the loklak server project the PR https://github.com/loklak/loklak_server/pull/1142 was merged that converts an md file automatically to an rst file.

Propose and implement a way to make this process part of the automatic generation process.

How can we generate a documentation site from md files and instead of keeping md and rst files in the original repository only host md files as source files?

### PR DESCRIPTION
**Pull request by pri22296**
Fixes #12 

The conversion is not 100% reliable. Sometimes leads to bad html.

### CODE REVIEW

**Comment by pri22296** [comment]
@mariobehling @niranjan94 @imujjwal96 @sch00lb0y Please review

**Comment by niranjan94** [comment]
@pri22296 thanks for the PR :) ... 

Could you give a sample of the generated HTML ?

And what sort of a _Bad HTML_ are we looking at ? What are some areas that this fails ?

**Comment by pri22296** [comment]
@niranjan94 Link to my generated docs -  https://pri22296.github.io/testYaydoc/
Here README.md has been used.

You can see that the generated html has some minor errors because of automatic markdown to rst conversion. The conversion step causes some errors.

**Comment by niranjan94** [comment]
Hmmm ... Okay ... Looks okay for now. We'll go ahead with this.

**Comment by pri22296** [comment]
But the user currently has no way to correct those errors. How do we handle that? I am not able to think of a solution here, unless the user replaces their README.md with a README.rst.

**Comment by niranjan94** [comment]
@pri22296 as a start, document the common types of errors/discrepancies caused during the conversion in a separate issue. We'll continue this discussion there.

**Pull request merged**
