### PR TITLE
Fixes #390 Change color of callout on build status

### LINKED ISSUE #390: Show status and change colour of callout based on status of build
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

Looking at the logs, a user cannot find if the build was successful or not. In order to determine the status, user will have to search for it in the logs. Such a UX is not desired
image
### Expected behaviour

Change the colour of callout and also show status with the metadata in order to improve user experience.

### PR DESCRIPTION
**Pull request by imujjwal96**
## Related Issue

issue #390 
## Motivation and Context

Looking at the logs, a user cannot find if the build was successful or not. In order to determine the status, user will have to search for it in the logs. Such a UX is not desired. Change the colour of callout and also show status with the metadata in order to improve user experience.
## How Has This Been Tested?

Test at https://yaydoc6.herokuapp.com
## Screenshots (if appropriate):
https://yaydoc6.herokuapp.com/imujjwal96/mydoc/logs
image
https://yaydoc6.herokuapp.com/imujjwal96/mydoc/logs/2
image

## Types of changes

- [ ] Bug fix 
- [x] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by imujjwal96** [comment]
@pri22296 @sch00lb0y Please review.

**Comment by pri22296** [comment]
@imujjwal96 Why does the failed build shows `<Binary data>` in logs?

**Comment by imujjwal96** [comment]
@pri22296 I edited the status from success to failed. Making that change changed the binary data to a string -> `<Binary Data>`

**Comment by imujjwal96** [comment]
@pri22296 Anything else?

**Pull request merged**
