### PR TITLE
add clone via github token as fallback to ssh

### LINKED ISSUE #89: Allow usage via access token as a fallback on failure to clone via SSH url.
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

Since #87 was merged, the old behaviour of using an access token with an https url was removed.

### Expected behaviour

Yaydoc should try to clone via SSH url and on failure use the value of GITURL as fallback.

### PR DESCRIPTION
**Pull request by pri22296**
## Description

Earlier ssh setup was necessary to use yaydoc. I have added usage via a github access token if cloning via ssh fails.

## Related Issue

Fixes #89 

## Motivation and Context

This change would help with seeting up login via github on the webUI to enable existing projects without ssh setup to use yaydoc. to use this an environment variable named OAUTH_TOKEN needs to be setup.

## How Has This Been Tested?

Tested on my test repository.

## Types of changes

- [ ] Bug fix 
- [x] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by pri22296** [comment]
@sch00lb0y @imujjwal96 Please review

**Comment by imujjwal96** [comment]
I don't see the OAUTH_TOKEN being defined anywhere. Need to update the docs?

**Comment by pri22296** [comment]
I was planning to update it in the PR for Issue #90. should i do it here instead?

**Comment by imujjwal96** [comment]
Nah. It's fine

**Comment by pri22296** [comment]
@sch00lb0y I have fixed the type in the commit message

**Pull request merged**
