### PR TITLE
Fixes #364 Generate headings before toctrees instead of captions

### LINKED ISSUE #364: Captions of the toctree created by genindex.py do not render as headings
### This is a
- [x] Bug report
- [ ] Feature request

### Current behaviour

screenshot 208

The captions are rendered as plain text instead of a heading.

### Expected behaviour

Generate appropriate headings instead of captions in the index.

### PR DESCRIPTION
**Pull request by pri22296**
## Description

- Each section is now under a specific heading.
- The advantage is that they are also added to the sidebar irrespective of the theme.

## Related Issue

Fixes #364 

## How Has This Been Tested?

Deployment: https://yaydocx.herokuapp.com/

## Screenshots (if appropriate):
screenshot 209

## Types of changes

- [x] Bug fix 
- [ ] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by pri22296** [comment]
@imujjwal96 @sch00lb0y Please review

**Comment by imujjwal96** [comment]
Do we need this update?

**Comment by pri22296** [comment]
Without this there is no way to add subprojects and other documents in the doc_path to the sidebar irrespective of the theme.

**Comment by pri22296** [comment]
@imujjwal96 Preview without this PR: http://yaydoc.herokuapp.com/preview/priyamsingh.22296@gmail.com/583ad774-75fb-4894-a77a-aaa0c7bb2836_preview/

Preview with this PR: https://yaydocx.herokuapp.com/preview/priyamsingh.22296@gmail.com/e62a54f0-b1e8-4475-bdcf-45cd35bf9f88_preview/

Please compare both these outputs.

**Comment by imujjwal96** [comment]
if a theme shows both global toc and local toc on the left side?

**Comment by pri22296** [comment]
@imujjwal96 The thing is, by default a theme just shows the localtoc (Behaviour of most of the themes. Also the behavior of sphinx_fossasia_theme). Certain themes override this behavior and either just show the global toc or show both or sometimes shows the hidden toc. One such theme I could find is `sphinx_rtd_theme`. The existing implementation would mean that subprojects would be displayed on the sidebar only when using those certain themes. This implementation would mean that the subprojects would be properly displayed with themes with the default behaviour which are greater in number as compared to the other category by a significant percentage. Now what do you suggest? what should we do? Also if you specify what reservations you have with this implementation, I would be able more clearly answer those.

**Pull request merged**
