### PR TITLE
Fixes #307 Add check for repository's permission

### LINKED ISSUE #307: Application crashes when the user tries to register non-accessible repository
### This is a
- [x] Bug report
- [ ] Feature request

### Current behaviour

Since we are showing all of an organization's repository that the user has access to, we are letting them perform the Register action on them as well.
image

### Expected behaviour

Either don't show those repositories at all or show a failure message

### PR DESCRIPTION
**Pull request by imujjwal96**
## Related Issue

issue: #307 

## How Has This Been Tested?

https://yaydoc7.herokuapp.com

## Types of changes

- [x] Bug fix 
- [ ] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by imujjwal96** [comment]
@pri22296  @sch00lb0y  Please review

**Comment by pri22296** [comment]
Application error on signing in to ci

**Comment by imujjwal96** [comment]
there was an error in the mongodb server. Please review again.

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by imujjwal96** [comment]
@mariobehling  Resolved conflicts.

**Pull request merged**
