### PR TITLE
Fixes #82 & #63 Set default values (spaces allowed) in Environment Variables  

### LINKED ISSUE #82: Error while deploying documentation using CircleCI
### This is a
- [x] Bug report
- [ ] Feature request

### Current behaviour

image

Link: https://circleci.com/gh/imujjwal96/mydoc/11

circle.yml
image

After we run sphinx-quickstart, a folder named Bhardwaj is created in Circle CI.
The same doesn't happen in Travis CI

### PR DESCRIPTION
**Pull request by imujjwal96**
## Description

Added `"` before and after variable names

## Related Issue

Issue: #82 & #63 

## How Has This Been Tested?

CircleCI Link: https://circleci.com/gh/imujjwal96/mydoc/16
## Types of changes

- [x] Bug fix 
- [ ] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by pri22296** [comment]
@imujjwal96 This also means that AUTHOR, PROJECTNAME and VERSION are no longer required variables. If that is the case, I would suggest `development` as the default VERSION instead of a blank string and also to update the README

**Comment by mariobehling** [comment]
Please resolve the conflicts.

**Comment by imujjwal96** [comment]
@pri22296 What about AUTHOR and PROJECTNAME
Shouldn't we take any default name for them. Like owner of the repository and repo name

**Comment by pri22296** [comment]
Yeah ideally we should. I even mentioned it in Issue #63 . But since building and publishing were seperated into 2 scripts, using GITURL in the build script seems wrong. Any other way to obtain the owner's and repository's name?

**Comment by imujjwal96** [comment]
@pri22296 Travis stores the default environment variable 
TRAVIS_REPO_SLUG: The slug (in form: owner_name/repo_name) of the repository currently being built.

We can split the array with http://www.linuxquestions.org/questions/programming-9/bash-shell-script-split-array-383848/#post3270796 and use them

**Comment by pri22296** [comment]
Can we use git config to obtain user name and repo name? that way it wouldn't be Travis specific.

**Comment by imujjwal96** [comment]
Ran git config --list in a sample repo.
Values returned:

    core.pager=
    core.repositoryformatversion=0
    core.filemode=true
    core.bare=false
    core.logallrefupdates=true
    remote.origin.url=https://github.com/imujjwal96/mydoc.git
    remote.origin.fetch=+refs/heads/master:refs/remotes/origin/master
    branch.master.remote=origin
    branch.master.merge=refs/heads/master

**Comment by pri22296** [comment]
So we need to parse remote.origin.url and extract repo and author name. since PR #87 already added a REPO variable which contains the url, can you make those changes?

**Comment by pri22296** [comment]
Since this also fixes #63 , please update the title and description of the PR

**Comment by pri22296** [comment]
@imujjwal96 Please update the README's Default section. also could you squash your commits?

**Comment by imujjwal96** [comment]
Because of that Merge, I am unable to squash the commits

**Comment by pri22296** [comment]
okay leave that. In the future I would suggest to pull with the --rebase flag. That way no merge commits would be created and it would be easy to squash commits.

**Comment by imujjwal96** [comment]
Yes, I did test them. Any problem?

**Comment by pri22296** [comment]
No problem as such. I was just conforming because the build log you shared in the description does not uses default values. If you did test them, that's fine.

**Pull request merged**
