### PR TITLE
Fixes #386 Show only metadata in log history

### LINKED ISSUE #386: Show only the metadata in log history instead of complete logs
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

Currently, we retrieve complete logs of all the builds at once. This would consume a lot of our resources and hence should be avoided.
image

### Expected behaviour

Retrieve only the metadata for each log and expand a specific log when specified
image

### PR DESCRIPTION
**Pull request by imujjwal96**
## Description

* Retrieve only the metadata of logs for `:owner/:reponame/logs`
* Show detailed log at `:owner/:reponame/logs/:buildnumber`
* Update views conforming changes
## Related Issue

issue: #386 
## Motivation and Context

Currently, we retrieve complete logs of all the builds at once. This would consume a lot of our resources and hence should be avoided. Retrieve only the metadata for each log and expand a specific log when specified
## How Has This Been Tested?

Test at https://yaydoc6.herokuapp.com
(http://yaydoc6.herokuapp.com/imujjwal96/mydoc/logs/2) & (http://yaydoc6.herokuapp.com/imujjwal96/mydoc/logs)
## Screenshots (if appropriate):
image
image

## Types of changes

- [ ] Bug fix 
- [x] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by imujjwal96** [comment]
@pri22296 @sch00lb0y  Please review.

**Comment by imujjwal96** [comment]
@pri22296 @sch00lb0y Please review.

**Comment by pri22296** [comment]
@imujjwal96 Why does http://yaydoc7.herokuapp.com/imujjwal96/prelimQuiz/logs/2 show status failed when the logs show success?

**Comment by imujjwal96** [comment]
@pri22296 This issue has been resolved here https://github.com/fossasia/yaydoc/pull/389/files#diff-a3ad650632783b799eceb858fcb9a9d5R155. It was reading the build number and updating  logs of the previous build

**Comment by imujjwal96** [comment]
@pri22296 @sch00lb0y Please review.

**Pull request merged**
