### PR TITLE
Fixes #86: eslint config added

### LINKED ISSUE #86: Fix codacy Issues
There are various issues from before pylint was integrated. They should be fixed.

### PR DESCRIPTION
**Pull request by sch00lb0y**
## Description

I have disable some eslint config which causing problem in the codacy.
I have disabled:
- `new-cap` 
- `security_detect-child-process`
## Related Issue

#86 
## Types of changes

- [x] Bug fix 
- [ ] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by pri22296** [comment]
Regarding `detect-child-process`, it seems to be a security issue. https://blog.liftsecurity.io/2014/08/19/Avoid-Command-Injection-Node.js/ explains it pretty well. I think switching off that warning might not be a good idea. @imujjwal96 your views?

**Comment by imujjwal96** [comment]
I agree with you. @pri22296 . Thank you for sharing the article. I have actually already worked on using spawn in place of exec as that will be required to get logs using Socket.io. After #94 is merged, I'll integrate that into the system and send another PR

**Comment by pri22296** [comment]
sounds good. Let's merge #94 and then solve some of the issues in a seperate PR. as for this PR, @sch00lb0y please reenable `detect-child-process`

**Comment by sch00lb0y** [comment]
@pri22296 that is an outdated article. @imujjwal96  for `spawn` also you have to use `child_process` module.

**Comment by sch00lb0y** [comment]
I have made changes @pri22296

**Comment by pri22296** [comment]
Looks good. @imujjwal96 any other warnings you might want to disable?

**Comment by imujjwal96** [comment]
Nopsie.

**Pull request merged**
