### PR TITLE
Added header with menu and footer with version data

### LINKED ISSUE #433: Update the UI of the homepage
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

Currently UI of App Generator is lacking Top navbar, Menu item and Version deployment info
### Expected behaviour

* Add top bar similar to Open Event frontend
* Add menu like Google/Susper on the top right corner (http://susper.com/)
* Add Version deployment info to the bottom like http://staging.loklak.org

### PR DESCRIPTION
**Pull request by jajodiaraghav**
## Description

- Add top bar similar to Open Event frontend
- Add menu like Google/Susper on the top right corner (http://susper.com/)
- Add Version deployment info to the bottom like http://staging.loklak.org

## Related Issue

Fixes #433 

## Motivation and Context

Adds a Header and a Footer, improvement in UI

## Screenshots (if appropriate):
screencapture-localhost-3001-1507469638499

## Types of changes

- [ ] Bug fix 
- [x] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by imujjwal96** [comment]
@jajodiaraghav  Show a sample deployment (preferably heroku) and a screenshot as well!

**Comment by jajodiaraghav** [comment]
@imujjwal96 I have added the screenshot. Although, deploying on heroku asks for a lot of keys such as:
GITHUB_CLIENT_ID
GITHUB_CLIENT_SECRET
HEROKU_CLIENT_ID
HEROKU_CLIENT_SECRET
HOSTNAME

How can I get these values. Also, Does a contributor has to deploy to heroku each time he makes a PR to yaydoc?

Thanks

**Comment by imujjwal96** [comment]
For this and similar PRs, in which these keys aren't used, random values suffice. However, if you contribute to other parts of the project, you would require registering a sample Github OAuth application and a Heroku OAuth application. You'll receive these values when you register. 

`HOSTNAME` is a url where your project/sampledeployment will be hosted (like yaydoc.herokuapp.com etc) .

> Does a contributor has to deploy to heroku each time he makes a PR to yaydoc?

It is recommended to show a sample deployment so that it becomes easier for reviewers to review and approve your PR.

**Comment by jajodiaraghav** [comment]
Deployed Link: https://demo439.herokuapp.com/

**Comment by imujjwal96** [comment]
There is an unexpected behavior when shrinking the browser width! I hope this screenshot is self-explanatory

image

**Comment by jajodiaraghav** [comment]
@imujjwal96 Updated the PR. Please review :)

**Comment by jajodiaraghav** [comment]
Whom should I ask to merge this?

**Comment by imujjwal96** [comment]
I can merge it, but i think it'd be better if another contributor can have a look at it.
@pri22296 @sch00lb0y

**Comment by sch00lb0y** [comment]
@jajodiaraghav good work!!

**Pull request merged**
