### PR TITLE
Fixes #190 add support for themes with different distribution and package name

### LINKED ISSUE #190: Add support for themes with different package and distribution names
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

Currently we assume that the `distribution name` and `package name` are the same (`distribution name` is what we pip install and `package name` is what we import) . but this may not be the case for all themes such as

| Dist name | Package name |
|------------|----------------|
| Flask-Sphinx-Theme | flask_sphinx_theme |
| mdn-sphinx-theme | mdn_theme |

Currently I plan to solve this by package inspection using `pkg_resources` to get the package name to import

### PR DESCRIPTION
**Pull request by pri22296**
## Description

- Added 2 new themes to the webUI
  - Flask-Sphinx-Themes
  - sphinxjp.themes.sphinxjp
- Use `pkg_resources` to find package instead of importing and accessing `__file__`

## Related Issue

Fixes #190 

## Motivation and Context

The earlier method to search a theme was to import the theme and get the location of the `__init__.py` file using the `__file__` attribute of the imported module and then search for `theme.conf` from there. This created several problems such as when package name and distribution name differ and when distribution name contained `.`(python has special rules for importing packages with `.`)  .

The new method uses pkg_resources to read the metadata of the distribution and from there build the path by using joining `dist.location` (which is usually the site-packages dir) and the first entry from `top_level.txt`. 

Overall this should be a more robust solution. 

## Types of changes

- [ ] Bug fix 
- [x] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by pri22296** [comment]
@imujjwal96 @sch00lb0y Please review

**Comment by imujjwal96** [comment]
sphinxjp.themes.sphinxjp isn't working

**Comment by pri22296** [comment]
It seems packages with `.` in their names could not be used here. I could make a special case for packages with `.` in their names but it feels hackish. Let me try if i can find a better solution!

**Comment by pri22296** [comment]
@imujjwal96 I have updated the code. should work in all cases.

**Comment by pri22296** [comment]
@sch00lb0y Please review this

**Pull request merged**
