### PR TITLE
Fixes #106 add autogeneration of index.rst

### LINKED ISSUE #106: Auto generate index.rst if not present
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

without index.rst the build fails.

### Expected behaviour

if index.rst is not present, a minimal index.rst should be generated.

### PR DESCRIPTION
**Pull request by pri22296**
## Description

 - The `genindex.py` script walks the `DOCPATH` directory to look for all `.md` and `.rst` files and and groups files in a single directory into a `toctree`. That way a user could just logically place similar files in separate directories and we would be able to generate multiple sections according to that.
- It also check if a `README.rst` or `README.md` is present in the root, and if that is the case, includes it from the generated index.
- The section titles are also appropriately named from the directory names(eg. if directory name is `installation_options`, caption would be `Installation Options`). Files which are not under any sub-directory are grouped into a separate `toctree` and captioned `Contents`.

## Related Issue

Fixes #106 

## Motivation and Context

Currently, If an index.rst is not present, the build fails. This PR enables yaydoc to handle that case by auto generating a minimal index.rst.

## How Has This Been Tested?

Tested on travis
Build log: https://travis-ci.org/pri22296/testYaydoc2/builds/244058155

## Screenshots (if appropriate):

Here is a sample index.rst generated from the following directory structure at
https://github.com/pri22296/testYaydoc2/tree/master/docs

screenshot 150

## Types of changes

- [ ] Bug fix 
- [x] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by imujjwal96** [comment]
What's the logic behind the generation?

**Comment by pri22296** [comment]
@imujjwal96 I have updated the description with the logic behind the generation

**Comment by imujjwal96** [comment]
Why display the index.rst file in the log.
you  know it is a very small block.

**Comment by pri22296** [comment]
Since we also support fully markdown projects, there may be users who aren't aware of the `rst` syntax, I added the index.rst to the log so that it would provide an easy template for users who wish to override certain elements without needing to learn to write `rst`. If it seems unnecessary, i would remove it.

**Comment by imujjwal96** [comment]
Cannot say if it is uneccesary or not. 
Is it possible if we could give a link to the index.rst file which the user, if wants, can check?

**Comment by pri22296** [comment]
That would require uploading the generated file somewhere. any ideas how to do it?

**Comment by imujjwal96** [comment]
Pastebin maybe? @pri22296

**Comment by pri22296** [comment]
would it be fine if that is done in a seperate PR? for now i'll just remove the `cat` statement?

**Comment by imujjwal96** [comment]
@pri22296 fine by me.

**Comment by pri22296** [comment]
@sch00lb0y Please review

**Comment by pri22296** [comment]
@imujjwal96 I was working on pasting index to pastebin. I was saving the pastebin dev key in as an environment variable. How do i let other users, use yaydoc with travis without needing their own pastebin dev key?

**Comment by pri22296** [comment]
@niranjan94 merge this?

**Comment by mariobehling** [comment]
@pri22296 Pastebin is not good. We don't want to build dependencies on more and more services. Please open a dedicated issue for this topic.

**Comment by imujjwal96** [comment]
We can discuss this in https://github.com/fossasia/yaydoc/issues/148

**Comment by pri22296** [comment]
This PR hasn't integrated with pastebin. as @imujjwal96 a seperate issue has been opened for this #148 . meanwhile we can merge this PR.

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by pri22296** [comment]
@mariobehling fixed the merge conflicts

**Pull request merged**
