### PR TITLE
Fixes #32 fix build failure if index.rst is in root

### LINKED ISSUE #32: Cannot have index.rst file in the root directory.
When I attempted to generate documentation of my project through yaydoc, there was an issue that when the index.rst file is kept in the root directory setting DOCPATH as `/` and `./` didn't work.
Eventually had to copy the index.rst file in `docs` folder.

### PR DESCRIPTION
**Pull request by pri22296**
## Description

The build failed because the temporary directories were being copied to the yaydoctemp dir which also included a recursive copying. The temporary directories were handles as follows

- I have moved the `yaydocvenv` dir to the `HOME` dir.
- `yaydocclone` is being deleted as it is no longer needed before copying
- `yaydoctemp` is being excluded by the `--exclude` flag of rsync

One change this PR makes is that, DOCPATH no longer needs a trailing slash. To refer to root, it should be set as `.`

## Related Issue

Fixes #32 

## How Has This Been Tested?

I have tested it with my own test repository.

Generated Docs - https://pri22296.github.io/testYaydoc2/
Travis Build - https://travis-ci.org/pri22296/testYaydoc2

## Types of changes

- [x] Bug fix 
- [ ] New feature

## Checklist:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only one commit per issue.

### CODE REVIEW

**Comment by pri22296** [comment]
@imujjwal96 @sch00lb0y Please review

**Comment by imujjwal96** [comment]
I guess you'll again have to create a test branch with your local configs.
I used 
- wget https://raw.githubusercontent.com/pri22296/yaydoc/master/generate.sh

and got [this](https://travis-ci.org/imujjwal96/prelimQuiz/jobs/238649302) exception in travis
also something weird happened in my [repo](https://github.com/imujjwal96/prelimQuiz/commit/950ac05233f957d777c99e34efefdefe40187827)

**Comment by pri22296** [comment]
I'm sorry, I deleted my test branch. i'll create it now.

**Comment by pri22296** [comment]
@imujjwal96 You need to create a index.rst in the root. Also that exception is caused by the filter added in #57 . @sch00lb0y Please look into this.

**Comment by imujjwal96** [comment]
https://github.com/imujjwal96/prelimQuiz/tree/docs
Its in the root directory already

**Comment by pri22296** [comment]
@imujjwal96 sorry, i was looking at the master branch. Once @sch00lb0y fixes the error, the build should pass.

**Comment by imujjwal96** [comment]
Raised an issue for it #66

**Comment by sch00lb0y** [comment]
@pri22296 I have solved the bug. @imujjwal96 could you test this pr with python travis for now.

**Comment by mariobehling** [comment]
Please resolve merge conflicts.

**Comment by pri22296** [comment]
@sch00lb0y @imujjwal96 I have updated the description to include the travis build log and the generated docs. Please review,

**Pull request merged**
